### PR TITLE
Hotfix/AdvancedOptions

### LINKED ISSUE #184: [BUG]LogObjectNotFound  not implemented correctly
**Describe the bug**  
I was happy to see you implemented the LogObjectNotFound  option in Faster.
Unfortunatly it does not work. You need to implement it as a class called AdvancedOptions. In the Server.cfg needs to be:

```

class AdvancedOptions
{
    LogObjectNotFound = false;
};

```

**To Reproduce**  
You can reproduce it by running any mission on a server and check the log. There should be no Object not found messeges...but there still are these messages.

**Screenshots**  
This is how it does work when you enter the code in the Mission selecto overwrite
image

**OS Version (required):**  
 - OS: Windows 10 
 - FASTER Version 1.9e

### PR DESCRIPTION
**Pull request by jupster**
## Description

Fixes Advanced Options

## Motivation and Context

Closes [184](https://github.com/Foxlider/FASTER/issues/184)

## How Has This Been Tested?

With tears
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

*Still to fix Output to update on click rather then on click of something outside of `Advanced Options` 🟢

### CODE REVIEW

**Comment by jupster** [comment]
Sonar out here emailing me now 😑

File: FASTER/Models/ServerCfg.cs [hunk 1]
```diff
@@ -811,13 +764,94 @@ public string ServerCfgContent
...
+        {
+            get => AdvancedOptionsContent;
+            set
+            {
+                AdvancedOptionsContent = value;
+                RaisePropertyChanged("AdvancedOptionsContent");
+            }
+        }
+
+        public Advancedoptions()
```
Comment (jupster) [inline FASTER/Models/ServerCfg.cs:839]: [L839-L851](https://github.com/Foxlider/FASTER/pull/186/files#diff-9babbf2c42ae3235cb955d5b6eb360c09935b7606dd78683185323b5a6888263R839-R851) needs to be changed

File: FASTER/FASTER.csproj [hunk 2]
```diff
@@ -1,4 +1,5 @@
 <Project Sdk="Microsoft.NET.Sdk">
+
```
Comment (jupster) [inline FASTER/FASTER.csproj:2]: remove extra spaces

File: FASTER/Models/ServerCfg.cs [hunk 3]
```diff
@@ -811,13 +764,94 @@ public string ServerCfgContent
                 RaisePropertyChanged("ServerCfgContent");
             }
         }
-
+
```
Comment (jupster) [inline FASTER/Models/ServerCfg.cs:767]: Remove whitespace

File: FASTER/Models/ServerProfile.cs [hunk 4]
```diff
@@ -22,13 +22,14 @@ public ServerProfileCollection()
...
         internal static void AddServerProfile(string profileName)
         {
-            var currentProfiles = Properties.Settings.Default.Profiles;
+            var currentProfiles                      = Properties.Settings.Default.Profiles;
             var p = new ServerProfile(profileName);
-            p.ServerCfg.ServerCfgContent     = p.ServerCfg.ProcessFile();
-            p.BasicCfg.BasicContent          = p.BasicCfg.ProcessFile();
-            p.ArmaProfile.ArmaProfileContent = p.ArmaProfile.ProcessFile();
+            p.ServerCfg.ServerCfgContent             = p.ServerCfg.ProcessFile();
+            p.ServerCfg.ServerCfgContent             = p.AdvancedOptions.ProcessFile();
```
Comment (jupster) [inline FASTER/Models/ServerProfile.cs:28]: go over this file again as it might be why ProcessFile isn't working

**Comment by jupster** [comment]
it is implemented properly. Output fixed as well. Just need to fix what i broke this push.

**Comment by jupster** [comment]
Prepare
```
class sockets {
    MaxBandwidth = "12Mbps";     // Per-client cap
    initBandwidth = "2Mbps";     // Supports weaker ISPs
};
```
Prepare
```
-keysFolder= command line parameter
```
